### ISSUE TITLE
[ISSUE] Crash on enable on Android emulator

### ISSUE THREAD

**Issue by SynapseScribe** [ukanth/afwall#1125]
**Describe the bug**
On fresh afwall install, after granting root on magisk canary and trying to enable firewall, app crashes.

**Firewall Logs**
After first crash, will crash on any subsequent app open. I cannot get the logs.

**Smartphone (please complete the following information):**
Android Emulator (Studio) - api 29 x86 (Q - 10)

**Additional context**

**Comment by ukanth** [comment]
Android 10 - API 29 x86, it's running fine.

**Comment by SynapseScribe** [comment]
Which magisk version should I use? With current stable/canary, it didn't work.

**Comment by SynapseScribe** [comment]
I can confirm that afwall still crashes. Bug is still there, need to re-open.

Magisk was installed on android emulator via https://github.com/shakalaca/MagiskOnEmulator

**Comment by SynapseScribe** [comment]
Found the error in logcat:

FATAL EXCEPTION: main
Process: dev.ukanth.ufirewall, PID: 6024
java.lang.RuntimeException: Unable to start service dev.ukanth.ufirewall.service.FirewallService@5434be5 with Intent { cmp=dev.ukanth.ufirewall/.service.FirewallService }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
	at dev.ukanth.ufirewall.InterfaceTracker.setupBluetoothProfile(InterfaceTracker.java:116)
	at dev.ukanth.ufirewall.service.FirewallService.onStartCommand(FirewallService.java:185)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
	... 8 more
