### ISSUE TITLE
[ISSUE] Crash on enable on Android emulator

### ISSUE THREAD

**Issue by SynapseScribe** [ukanth/afwall#1132]
Describe the bug
On fresh afwall install, after granting root on magisk canary and trying to enable firewall, app crashes.

Firewall Logs
After first crash, will crash on any subsequent app open. I cannot get the logs.

Smartphone (please complete the following information):
Android Emulator (Studio) - api 29 x86 (Q - 10)

Additional context
Found the error in logcat:

FATAL EXCEPTION: main
Process: dev.ukanth.ufirewall, PID: 6024
java.lang.RuntimeException: Unable to start service dev.ukanth.ufirewall.service.FirewallService@5434be5 with Intent { cmp=dev.ukanth.ufirewall/.service.FirewallService }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
at android.app.ActivityThread.access$1800(ActivityThread.java:219)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference
at dev.ukanth.ufirewall.InterfaceTracker.setupBluetoothProfile(InterfaceTracker.java:116)
at dev.ukanth.ufirewall.service.FirewallService.onStartCommand(FirewallService.java:185)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
... 8 more

**Comment by SynapseScribe** [comment]
I can confirm that afwall still crashes when trying to enable it first time and instantly on successive app opens.

Latest canary magisk was installed on fresh android avs (android studio emulator) via https://github.com/shakalaca/MagiskOnEmulator

**Comment by SynapseScribe** [comment]
Same as: https://github.com/ukanth/afwall/issues/1125
Duplicate of #https://github.com/ukanth/afwall/issues/1125

**Comment by ukanth** [comment]
I use direct scripts provided by Magisk repo itself (built using code) and it works fine. I have not tested with these scripts

**Comment by SynapseScribe** [comment]
Which scripts and version of magisk more specifically? Can you please give me some reference for some steps to follow? Thank you!

**Comment by ukanth** [comment]
I use this one from Magisk -> https://github.com/topjohnwu/Magisk/blob/master/scripts/emulator.sh 

You need to compile everything (python is required). I don't have step-by-step intructions. May be I will write one.
