### ISSUE TITLE
Crash with java.lang.NoSuchMethodError when opening protocol

### ISSUE THREAD

**Issue by eku** [ukanth/afwall#1344]
**Describe the bug**
When opening the firewall protocol from the menu, AFwall instantly crashes.

**Firewall Logs**
N/A

**Smartphone (please complete the following information):**
 - Device: Xiaomi Max 2
 - Android OS: 7.1

**Additional context**

AFwall 3.5.3 with NFLOG target and log service enabled.

```
08-09 16:03:07.091  5086  5086 E AndroidRuntime: FATAL EXCEPTION: main
08-09 16:03:07.091  5086  5086 E AndroidRuntime: Process: dev.ukanth.ufirewall, PID: 5086
08-09 16:03:07.091  5086  5086 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method toInstant()Ljava/time/Instant; in class Ljava/util/Date; or its super classes (declaration of 'java.util.Date' appears in /system/framework/core-oj.jar)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at org.ocpsoft.prettytime.PrettyTime.setReference(PrettyTime.java:1355)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at dev.ukanth.ufirewall.log.LogRecyclerViewAdapter.pretty(LogRecyclerViewAdapter.java:166)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at dev.ukanth.ufirewall.log.LogRecyclerViewAdapter.onBindViewHolder(LogRecyclerViewAdapter.java:142)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at dev.ukanth.ufirewall.log.LogRecyclerViewAdapter.onBindViewHolder(LogRecyclerViewAdapter.java:35)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:751)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.View.layout(View.java:17838)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5754)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
08-09 16:03:07.091  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2389)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1467)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7005)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:644)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:836)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:203)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6247)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
08-09 16:03:07.092  5086  5086 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by amaa-99** [comment]
This seems to be the same issue addressed by:
[https://github.com/ukanth/afwall/pull/1337]
