### ISSUE TITLE
Unable to enable firewall: "Unable to  acquire root access !"

### ISSUE THREAD

**Issue by maremike** [ukanth/afwall#1394]
**Describe the bug**
I installed Afwall+ and cannot enable it. This app needs root access. I then proceeded to give it the following permissions (description):
RECEIVE_BOOT_COMPLETED, ACCESS_NETWORK_STATE, WRITE_EXTERNAL_STORAGE, INTERNET, ACCESS_WIFI_STATE
I went to the adb shell and entered following command: "pm grant dev.ukanth.ufirewall INTERNET" for instance.
To which I received to each permission a following error code:
Exception occurred while executing 'grant':
java.lang.IllegalArgumentException: Unknown permission: INTERNET
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1407)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1365)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:551)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:599)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2604)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:309)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7088)
        at android.os.Binder.shellCommand(Binder.java:1085)
        at android.os.Binder.onTransact(Binder.java:903)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4962)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7072)
        at android.os.Binder.execTransactInternal(Binder.java:1321)
        at android.os.Binder.execTransact(Binder.java:1280)

**Smartphone (please complete the following information):**
I am using the Samsung S20 FE with Android 13.

Would be great if there was any tutorial on how to get this app to work.

**Comment by maremike** [comment]
With this command the permissions are detected: "pm grant dev.ukanth.ufirewall android.permission.RECEIVE_BOOT_COMPLETED"
But then I get the following message with those permissions: RECEIVE_BOOT_COMPLETED, ACCESS_NETWORK_STATE, INTERNET, ACCESS_WIFI_STATE -> Permission ... requested by dev.ukanth.ufirewall is not a changeable permission type
And with this permission: WRITE_EXTERNAL_STORAGE -> Package dev.ukanth.ufirewall has not requested permission ...

**Comment by maremike** [comment]
Apparently I didnt know how rooting works. I need magisk and root.
