### ISSUE TITLE
3.6.1 donate crashes on Pixel 8 pro / cannot import setting backup

### ISSUE THREAD

**Issue by nutpantz** [ukanth/afwall#1397]
**Describe the bug**
after update from 3.6.0 to 3.6.1 app crashes almost immediately. i do see a toast "binary installed" 
if i uninstall and do a fresh install it will install BUT i cannot import settings from 3.6.0 it reports failed
( backup of settings created just before update)

**Firewall Logs**
no logs available 

**Smartphone (please complete the following information):**
 pixel 8 pro (arm64v8a only supported)
oem android 14 june 2024

**Additional context**
i will try and get system logs

FATAL EXCEPTION: pool-2-thread-1
Process: dev.ukanth.ufirewall.donate, PID: 12723
java.util.concurrent.RejectedExecutionException: Task com.topjohnwu.superuser.internal.JobTask$$ExternalSyntheticLambda0@4e9ed78 rejected from java.util.concurrent.ThreadPoolExecutor@c4dc51[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
	at com.topjohnwu.superuser.internal.JobTask.setResult(JobTask.java:60)
	at com.topjohnwu.superuser.internal.JobTask.run(JobTask.java:110)
	at com.topjohnwu.superuser.internal.ShellImpl.exec0(ShellImpl.java:258)
	at com.topjohnwu.superuser.internal.ShellImpl.processTasks(ShellImpl.java:265)
	at com.topjohnwu.superuser.internal.ShellImpl.$r8$lambda$s0PUNn9LoGilzQm1QDsbRoEjcGo(Unknown Source:0)
	at com.topjohnwu.superuser.internal.ShellImpl$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Fry-kun** [comment]
I'm getting the same error, config UI won't start at all.
With certain Magisk module updates, even the initial rules can't apply, causing a no-internet "lockup" (Magisk can't access internet because Afwall rules didn't finish applying, etc.)

Edit:
Pixel 9 Pro XL, Android 15 (Oct build)

Edit 2:
Seems that Android 15 prevents app downgrades, so I can't force install 3.6.0 while keeping the config (probably would work if I uninstall -- but that would make me lose all my settings)

Edit 3:
Backed up data using Swift Backup, uninstalled 1.6.1, installed 1.6.0, and restored data. 1.6.0 works fine so far!

Edit 4:
Exploring stuff with all options reset: AFWall crashes right away after enabling log service. Seems that might be a core issue

**Comment by nutpantz** [comment]
I wonder if this might be the issue that is causing the crash
https://github.com/ukanth/afwall/issues/1380

**Comment by Fry-kun** [comment]
Yup, that was it.
Used my build of 64bit nflog and it works..

**Comment by nutpantz** [comment]
> Yup, that was it. Used my build of 64bit nflog and it works..

Can you post exactly what you did to fix it? Kindergarten instructions.. lol
(Yes i know, download this and copy it there then change ownership and permission, i still fear having to start from scratch because i missed something).

**Comment by Fry-kun** [comment]
It's not exactly kindergarten level, kinda ugly.
And I'm not convinced that Afwall work properly after all that, anyway. The UI doesn't crash and it claims some stuff was blocked -- but so far all apps can access internet anyway :(

On a Linux host machine:
* Download a copy of the source code
* Check if you have ndk installed, install if you don't have it. Mine lives in `/usr/lib/android-sdk/ndk/10.4`
* In command line:
  * `cd afwall/external`
  * `export PATH="$PATH:/usr/lib/android-sdk/ndk/10.4"`
  * `make ARCH=arm64 nflog`
  * `adb root`
  * `adb push ../app/src/main/res/raw/nflog_arm64 /data/user/0/dev.ukanth.ufirewall/app_bin/` # may have to update the path if you're using `donate` version

HTH

**Comment by mj084** [comment]
@ukanth 

Is a new version with the "fix" described here planned?

**Comment by SynapseScribe** [comment]
Still getting error and afwall crashing sometimes


FATAL EXCEPTION: pool-2-thread-1
Process: dev.ukanth.ufirewall, PID: 6606
java.util.concurrent.RejectedExecutionException: Task com.topjohnwu.superuser.internal.JobTask$$ExternalSyntheticLambda0@537d4d8 rejected from java.util.concurrent.ThreadPoolExecutor@2afa031[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at com.topjohnwu.superuser.internal.JobTask.setResult(JobTask.java:60)
	at com.topjohnwu.superuser.internal.JobTask.run(JobTask.java:110)
	at com.topjohnwu.superuser.internal.ShellImpl.exec0(ShellImpl.java:258)
	at com.topjohnwu.superuser.internal.ShellImpl.processTasks(ShellImpl.java:265)
	at com.topjohnwu.superuser.internal.ShellImpl.$r8$lambda$s0PUNn9LoGilzQm1QDsbRoEjcGo(Unknown Source:0)
	at com.topjohnwu.superuser.internal.ShellImpl$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)



Afwall 3.6.1 + unlocker
Log target: LOG
