### ISSUE TITLE
Beta 2 UI Crash

### ISSUE THREAD

**Issue by an0n981** [ukanth/afwall#396]
UI crashes on launch

```
08-03 20:05:02.091 E/AndroidRuntime(10894): FATAL EXCEPTION: main
08-03 20:05:02.091 E/AndroidRuntime(10894): Process: dev.ukanth.ufirewall, PID: 10894
08-03 20:05:02.091 E/AndroidRuntime(10894): java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.ukanth.ufirewall/dev.ukanth.ufirewall.MainActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.os.Looper.loop(Looper.java:135)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.lang.reflect.Method.invoke(Native Method)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
08-03 20:05:02.091 E/AndroidRuntime(10894): Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.TimSort.mergeLo(TimSort.java:743)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.TimSort.mergeAt(TimSort.java:479)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.TimSort.mergeCollapse(TimSort.java:406)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.TimSort.sort(TimSort.java:210)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.TimSort.sort(TimSort.java:169)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.Arrays.sort(Arrays.java:2010)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at java.util.Collections.sort(Collections.java:1883)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at dev.ukanth.ufirewall.MainActivity.showApplications(MainActivity.java:750)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at dev.ukanth.ufirewall.MainActivity.selectFilterGroup(MainActivity.java:211)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at dev.ukanth.ufirewall.MainActivity.reloadPreferences(MainActivity.java:307)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at dev.ukanth.ufirewall.MainActivity.onStart(MainActivity.java:314)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.Activity.performStart(Activity.java:6006)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
08-03 20:05:02.091 E/AndroidRuntime(10894): 	... 11 more
```

**Comment by ukanth** [comment]
Could you please do a clean install and try ?

**Comment by an0n981** [comment]
Clean install worked, no custom sorting

**Comment by ukanth** [comment]
Thanks. Closing it now.
