### ISSUE TITLE
command 'iptables -A afwall-3g -j afwall-3g-postcustom' exited with status 2

### ISSUE THREAD

**Issue by shellshocker** [ukanth/afwall#471]
Hello,

I'm using AFWall+ 2.1.1 on Android 6.0.1 Nexus 7 (2012).
After disabling Custom Scripts AFWall+ will not load the custom rules. I fetched some info with logcat:

```
12-25 13:29:03.106  5284  5284 I AFWall  : command 'iptables -A afwall-3g -j afwall-3g-postcustom' exited with status 2
12-25 13:29:03.106  5284  5284 I AFWall  : Output:
12-25 13:29:03.106  5284  5284 I AFWall  : iptables v1.4.20: Couldn't find target `afwall-3g-postcustom'
12-25 13:29:03.106  5284  5284 I AFWall  : Try `iptables -h' or 'iptables --help' for more information.
```

In my ruleset there is nothing with 'iptables -A afwall-3g'. Just some drop rules with 'afwall' chain.
Maybe it's not working because Nexus 7 has not any 3g network interface.

After enabling:

```
12-25 13:41:48.484  5284  5284 D AFWall  : Starting root shell...
12-25 13:41:48.484  5284  5284 I AFWall  : [libsuperuser] [SU%] START
12-25 13:41:48.676  5284  5284 D AFWall  : Root shell is open
12-25 13:41:48.839  5284  5295 I art     : Background partial concurrent mark sweep GC freed 33605(2044KB) AllocSpace objects, 5(100KB) LOS objects, 24% free, 7MB/9MB, paused 1.085ms total 200.124ms
12-25 13:41:48.938  5284 19229 D OpenGLRenderer: endAllStagingAnimators on 0x5bb4c100 (ListPopupWindow$DropDownListView) with handle 0x5c1daeb0
12-25 13:41:50.219 27941 27941 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-25 13:41:50.229 27941 27941 D AndroidRuntime: CheckJNI is OFF
12-25 13:41:50.233 27941 27941 W app_process32_o: type=1400 audit(0.0:9972): avc: denied { write } for name="system@framework@boot.art" dev=mmcblk0p9 ino=425157 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=file permissive=0
12-25 13:41:50.350 27941 27941 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-25 13:41:50.353 27941 27941 W main    : type=1400 audit(0.0:9973): avc: denied { write } for name="arm" dev=mmcblk0p9 ino=425155 scontext=u:r:shell:s0 tcontext=u:object_r:dalvikcache_data_file:s0 tclass=dir permissive=0
12-25 13:41:50.472 27941 27941 E memtrack: Couldn't load memtrack module (No such file or directory)
12-25 13:41:50.472 27941 27941 E android.os.Debug: failed to load memtrack module: -2
12-25 13:41:50.492 27941 27941 I Radio-JNI: register_android_hardware_Radio DONE
12-25 13:41:50.572 27941 27941 D AndroidRuntime: Calling main entry com.android.commands.am.Am
12-25 13:41:50.612 27941 27941 D AndroidRuntime: Shutting down VM
12-25 13:41:50.698  1187  1187 I art     : Waiting for a blocking GC DisableMovingGc
12-25 13:41:50.703  1187  1198 I art     : CollectorTransition marksweep + semispace GC freed 1283(47KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 3MB/4MB, paused 48.728ms total 48.728ms
12-25 13:41:50.704  1187  1187 I art     : WaitForGcToComplete blocked for 5.860ms for cause DisableMovingGc
12-25 13:41:50.704  1187  1187 I art     : Starting a blocking GC DisableMovingGc
12-25 13:41:51.804 28011 28011 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-25 13:41:51.821 28011 28011 D AndroidRuntime: CheckJNI is OFF
12-25 13:41:51.949 28011 28011 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-25 13:41:52.048 28011 28011 E memtrack: Couldn't load memtrack module (No such file or directory)
12-25 13:41:52.048 28011 28011 E android.os.Debug: failed to load memtrack module: -2
12-25 13:41:52.061 28011 28011 I Radio-JNI: register_android_hardware_Radio DONE
12-25 13:41:52.121 28011 28011 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-25 13:41:52.128 28011 28011 D AndroidRuntime: Shutting down VM
12-25 13:41:53.506 28030 28030 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-25 13:41:53.515 28030 28030 D AndroidRuntime: CheckJNI is OFF
12-25 13:41:53.634 28030 28030 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-25 13:41:53.723 28030 28030 E memtrack: Couldn't load memtrack module (No such file or directory)
12-25 13:41:53.723 28030 28030 E android.os.Debug: failed to load memtrack module: -2
12-25 13:41:53.738 28030 28030 I Radio-JNI: register_android_hardware_Radio DONE
12-25 13:41:53.804 28030 28030 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-25 13:41:53.815 28030 28030 D AndroidRuntime: Shutting down VM
12-25 13:41:55.188 28040 28040 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-25 13:41:55.197 28040 28040 D AndroidRuntime: CheckJNI is OFF
12-25 13:41:55.312 28040 28040 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-25 13:41:55.409 28040 28040 E memtrack: Couldn't load memtrack module (No such file or directory)
12-25 13:41:55.409 28040 28040 E android.os.Debug: failed to load memtrack module: -2
12-25 13:41:55.425 28040 28040 I Radio-JNI: register_android_hardware_Radio DONE
12-25 13:41:55.491 28040 28040 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-25 13:41:55.504 28040 28040 D AndroidRuntime: Shutting down VM
12-25 13:41:56.520  5284 28010 I AFWall  : [libsuperuser] [SU%] WATCHDOG_EXIT
12-25 13:41:56.558  5284  5284 E AFWall  : libsuperuser error -1 on command '. /sdcard/Download/iptables.sh'
12-25 13:42:02.067  5284 12520 W MessageQueue: Handler (android.os.Handler) {9f0295f} sending message to a Handler on a dead thread
12-25 13:42:02.067  5284 12520 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {9f0295f} sending message to a Handler on a dead thread
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.Handler.post(Handler.java:326)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.widget.Toast$TN.hide(Toast.java:388)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.app.ITransientNotification$Stub.onTransact(ITransientNotification.java:55)
12-25 13:42:02.067  5284 12520 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
12-25 13:42:03.741   521   581 D WifiStateMachine: starting scan for "WLAN@Home"WPA_PSK with 2462
12-25 13:42:22.103   133   502 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
```

Problems with memtrack module? This seems ROM related.

**Comment by ukanth** [comment]
Can you try flush the rules and try again ?

**Comment by shellshocker** [comment]
@ukanth Thanks for answering.

I've done reboots, killed the UID, flushed the rules etc. Nothing changes. Here is my latest output, after enabling AFWall+. Info: It keeps saying "IPTables-Regeln werden angewendet". In English: "IPTables-Rules are applied".

```
12-28 16:25:08.108 24624 24624 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-28 16:25:08.119 24624 24624 D AndroidRuntime: CheckJNI is OFF
12-28 16:25:08.233 24624 24624 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-28 16:25:08.342 24624 24624 E memtrack: Couldn't load memtrack module (No such file or directory)
12-28 16:25:08.342 24624 24624 E android.os.Debug: failed to load memtrack module: -2
12-28 16:25:08.359 24624 24624 I Radio-JNI: register_android_hardware_Radio DONE
12-28 16:25:08.428 24624 24624 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-28 16:25:08.442 24624 24624 D AndroidRuntime: Shutting down VM
12-28 16:25:09.775 24632 24632 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-28 16:25:09.785 24632 24632 D AndroidRuntime: CheckJNI is OFF
12-28 16:25:09.904 24632 24632 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-28 16:25:10.000 24632 24632 E memtrack: Couldn't load memtrack module (No such file or directory)
12-28 16:25:10.000 24632 24632 E android.os.Debug: failed to load memtrack module: -2
12-28 16:25:10.013 24632 24632 I Radio-JNI: register_android_hardware_Radio DONE
12-28 16:25:10.077 24632 24632 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-28 16:25:10.091 24632 24632 D AndroidRuntime: Shutting down VM
12-28 16:25:11.389 24646 24646 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
12-28 16:25:11.396 24646 24646 D AndroidRuntime: CheckJNI is OFF
12-28 16:25:11.506 24646 24646 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
12-28 16:25:11.603 24646 24646 E memtrack: Couldn't load memtrack module (No such file or directory)
12-28 16:25:11.603 24646 24646 E android.os.Debug: failed to load memtrack module: -2
12-28 16:25:11.616 24646 24646 I Radio-JNI: register_android_hardware_Radio DONE
12-28 16:25:11.679 24646 24646 D AndroidRuntime: Calling main entry com.android.commands.settings.SettingsCmd
12-28 16:25:11.692 24646 24646 D AndroidRuntime: Shutting down VM
12-28 16:25:12.977 24410 24623 I AFWall  : [libsuperuser] [SU%] WATCHDOG_EXIT
```

No more log entries. I have to kill the UID via Settings -> Apps -> AFWall+ -> Forcefull quit.

**Comment by shellshocker** [comment]
Update:
On my Nexus 5 with 6.0.1 same script is working fine. So maybe it's ROM related.

**Comment by CHEF-KOCH** [comment]
> iptables v1.4.20: Couldn't find target `afwall-3g-postcustom'

Your current iptables binary simply not understand postcustom, that's all. Android 6 and default iptables is bugged/outdated and problematic.

**Comment by ukanth** [comment]
ROM related.
