### ISSUE TITLE
E/BandwidthController runIptablesCmd &  E/NetworkPolicy  throwing exc  

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#554]
```
327-885/? E/BandwidthController: Updating quota globalAlert failed (No such file or directory)
327-885/? I/ip6tables: ip6tables: Index of insertion too big.
327-885/? I/ip6tables: ip6tables terminated by exit(1)
327-885/? E/BandwidthController: runIptablesCmd(): res=1 status=256 failed /system/bin/ip6tables -w -I bw_FORWARD 2 -i rmnet0 --jump bw_costly_rmnet0
763-904/? E/QCOM PowerHAL: Failed to acquire lock.
327-885/? E/BandwidthController: Failed set quota rule
327-885/? E/BandwidthController: No such iface rmnet0 to delete
763-912/? E/NetworkPolicy: problem setting interface quota
                           java.lang.IllegalStateException: command '67 bandwidth setiquota rmnet0 9223372036854775807' failed with '400 67 Bandwidth command failed'
                               at com.android.server.NetworkManagementService.setInterfaceQuota(NetworkManagementService.java:1707)
                               at com.android.server.net.NetworkPolicyManagerService.setInterfaceQuota(NetworkPolicyManagerService.java:2556)
                               at com.android.server.net.NetworkPolicyManagerService.updateNetworkRulesLocked(NetworkPolicyManagerService.java:1314)
                               at com.android.server.net.NetworkPolicyManagerService$14.onReceive(NetworkPolicyManagerService.java:1138)
                               at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
                               at android.os.Handler.handleCallback(Handler.java:739)
                               at android.os.Handler.dispatchMessage(Handler.java:95)
                               at android.os.Looper.loop(Looper.java:148)
                               at android.os.HandlerThread.run(HandlerThread.java:61)
                            Caused by: com.android.server.NativeDaemonConnector$NativeDaemonFailureException: command '67 bandwidth setiquota rmnet0 9223372036854775807' failed with '400 67 Bandwidth command failed'
                               at com.android.server.NativeDaemonConnector.executeForList(NativeDaemonConnector.java:444)
                               at com.android.server.NativeDaemonConnector.execute(NativeDaemonConnector.java:345)
                               at com.android.server.NativeDaemonConnector.execute(NativeDaemonConnector.java:340)
                               at com.android.server.NetworkManagementService.setInterfaceQuota(NetworkManagementService.java:1704)
                               at com.android.server.net.NetworkPolicyManagerService.setInterfaceQuota(NetworkPolicyManagerService.java:2556) 
                               at com.android.server.net.NetworkPolicyManagerService.updateNetworkRulesLocked(NetworkPolicyManagerService.java:1314) 
                               at com.android.server.net.NetworkPolicyManagerService$14.onReceive(NetworkPolicyManagerService.java:1138) 
                               at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882) 
                               at android.os.Handler.handleCallback(Handler.java:739) 
                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                               at android.os.Looper.loop(Looper.java:148) 
                               at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by ukanth** [comment]
Please provide more information.

**Comment by ukanth** [comment]
This is not AFWall+ logs. It's happening at Android level.
