### ISSUE TITLE
pattern unlock problem

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#556]
when go to afwall use pattern then i get:
then need go second time and its fine when i use pattern 

![screenshot_20160805-175201](https://cloud.githubusercontent.com/assets/10565704/17453891/efdbbe0e-5b74-11e6-823f-b41a54effa78.png)

could be related to log entry 

```
5529-5529/dev.ukanth.ufirewall I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
5529-5529/dev.ukanth.ufirewall W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView

```

  or    <<<<<<<<

```
25776-25788/dev.ukanth.ufirewall W/MessageQueue: Handler (android.os.Handler) {23d9b8e} sending message to a Handler on a dead thread
                                                 java.lang.IllegalStateException: Handler (android.os.Handler) {23d9b8e} sending message to a Handler on a dead thread
                                                     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                     at android.os.Handler.enqueueMessage(Handler.java:631)
                                                     at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                     at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                     at android.os.Handler.post(Handler.java:326)
                                                     at android.widget.Toast$TN.hide(Toast.java:393)
                                                     at android.app.ITransientNotification$Stub.onTransact(ITransientNotification.java:55)
                                                     at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by ukanth** [comment]
What version of Android you are using ?

**Comment by c3ph3us** [comment]
6.0.1 r61

**Comment by ukanth** [comment]
Please test it with latest version and reopen if required.
